# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'Обработка'), (2, 'Принят'), (3, 'Отменён'), (4, 'Отправлен'), (5, 'Ждёт оплаты'), (6, 'Оплачен'), (7, 'Перевод'), (8, 'Возврат'), (9, 'Дубликат'), (10, 'Ошибка')])),
            ],
        ),
    ]
